name: build-on-chrome
on:
  pull_request:
    branches:
      - 'master'
      - 'release/**'
    types: [opened, reopened, edited, synchronize]
    paths:
      - '*.js'
      - 'test/**'
jobs:
  buildChrome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test Chrome
      run: |
        npm i
        npm run test.Chrome
