name: build-on-firefox
on:
  pull_request:
    branches:
      - 'master'
      - 'release/**'
      - 'dev'
    types: [opened, reopened, edited, synchronize]
    paths:
      - '*.js'
      - 'test/**'
jobs:
  # scan code using CodeQL
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - 'javascript'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  buildFF:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
    - uses: actions/checkout@v1
    - name: Test Firefox
      run: |
        npm i
        npm run test.FF
