name: publish
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - '*.js'
      - '!karma.conf.js'
      - 'example/index.html'
      - 'package.json'
env:
  AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_KEY_SECRET: ${{ secrets.AWS_KEY_SECRET }}
  BUCKET: ${{ secrets.S3_PUBLIC_BUCKET }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Test
      run: npm test
    - name: Upload files to S3 bucket
      uses: kaskadi/action-s3cp@master
